title: Tarun Kumar Yadav
description: Personal webpage of Tarun Kumar Yadav.
url: "https://tkyiitd.github.io"
baseurl: ""
lang: en-IN

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - tmp
